version: '3.8'

services:
  postgresql:
    container_name: ms-client_postgresql
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: client
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty


