version: '3.8'

services:
  web:
    image: tomcat
    volumes:
      - .build/libs/weather-0.0.1-SNAPSHOT-plain.war:/usr/local/tomcat/webapps/weather-0.0.1-SNAPSHOT-plain.war
    ports:
      - '8082:8080'
  postgresql:
    container_name: weather_postgresql
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
  key-cloak-db:
    container_name: key-cloak-db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
  key-cloak:
    container_name: key-cloak
    image: bitnami/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_DATABASE_VENDOR: postgresql
      DB_ADDR: key-cloak-db
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: qwerty
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - key-cloak-db