server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: weather

  jpa:
    show-sql: true

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:weather}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:qwerty}