server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: weather
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Weather
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  jpa:
    show-sql: true

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:weather}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:qwerty}
jwt:
  auth:
    converter:
      resource-id: weather-rest-api
      principle-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: deposit-service
    description: This is deposit-service application

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    groups-order: DESC
    path: /swagger-ui.html
    operationsSorter: method
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'

logging:
  pattern:
    console: "%clr(%d{dd:yy:MM:HH:mm}){faint}%clr(${LOG_LEVEL_PATTERN:-%-5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: info
    com.andersen.weather.service: debug
